In [17]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import locale
locale.setlocale( locale.LC_ALL, 'en_US.UTF-8' )

'en_US.UTF-8'

In [18]:
df_gdp = pd.read_csv("./GDP/GDP_annual_growth_NEW.csv")
gdp = pd.DataFrame()
gdp['Country'] = df_gdp.pop('Country Name')
gdp['GDP Growth']    = df_gdp.pop('2020')
gdp.dropna(axis=0,inplace=True)
gdp

                         Country  GDP Growth
1    Africa Eastern and Southern   -2.929511
2                    Afghanistan   -1.934778
3     Africa Western and Central   -0.934728
4                         Angola   -4.040510
5                        Albania   -3.311239
..                           ...         ...
260                        Samoa   -2.742567
261                       Kosovo   -6.888013
263                 South Africa   -6.959604
264                       Zambia   -3.016189
265                     Zimbabwe   -8.000000

[228 rows x 2 columns]

In [40]:
dataframes = []
for i in range(1,5):
    df1 = pd.read_csv("./Ookla/fixed_year_2020_quarter_0{}.csv".format(i))
    df2 = pd.read_csv("./Ookla/fixed_year_2021_quarter_0{}.csv".format(i))
    df1['Avg. Avg U Kbps'] = df1['Avg. Avg U Kbps'].map(lambda x: locale.atof(x))
    df2['Avg. Avg U Kbps'] = df2['Avg. Avg U Kbps'].map(lambda x: locale.atof(x))
    df1['Avg. Avg D Kbps'] = df1['Avg. Avg D Kbps'].map(lambda x: locale.atof(x))
    df2['Avg. Avg D Kbps'] = df2['Avg. Avg D Kbps'].map(lambda x: locale.atof(x))
    df1['Avg Lat Ms'] = df1['Avg Lat Ms'].map(lambda x: float(x))
    df2['Avg Lat Ms'] = df2['Avg Lat Ms'].map(lambda x: float(x))
    dfout = pd.DataFrame()
    dfout['Mobile']   = np.zeros(np.shape(df1['Name']))
    dfout['Country']  = df1.pop('Name')
    dfout['Upload']   = np.subtract(df2.pop('Avg. Avg U Kbps'), df1.pop('Avg. Avg U Kbps'))
    dfout['Download'] = np.subtract(df2.pop('Avg. Avg D Kbps'), df1.pop('Avg. Avg D Kbps'))
    dfout['Latency']  = np.subtract(df2.pop('Avg Lat Ms'),df1.pop('Avg Lat Ms'))
    dfout.dropna(axis=0,inplace=True)
    dfout = dfout.merge(gdp, how='inner', on='Country')
    dataframes.append(dfout)

for i in range(1,5):
    df1 = pd.read_csv("./Ookla/mobile_year_2020_quarter_0{}.csv".format(i))
    df2 = pd.read_csv("./Ookla/mobile_year_2021_quarter_0{}.csv".format(i))
    df1['Avg. Avg U Kbps'] = df1['Avg. Avg U Kbps'].map(lambda x: locale.atof(x))
    df2['Avg. Avg U Kbps'] = df2['Avg. Avg U Kbps'].map(lambda x: locale.atof(x))
    df1['Avg. Avg D Kbps'] = df1['Avg. Avg D Kbps'].map(lambda x: locale.atof(x))
    df2['Avg. Avg D Kbps'] = df2['Avg. Avg D Kbps'].map(lambda x: locale.atof(x))
    df1['Avg Lat Ms'] = df1['Avg Lat Ms'].map(lambda x: float(x))
    df2['Avg Lat Ms'] = df2['Avg Lat Ms'].map(lambda x: float(x))
    dfout = pd.DataFrame()
    dfout['Mobile']   = np.ones(np.shape(df1['Name']))
    dfout['Country']  = df1.pop('Name')
    dfout['Upload']   = np.subtract(df2.pop('Avg. Avg U Kbps'), df1.pop('Avg. Avg U Kbps'))
    dfout['Download'] = np.subtract(df2.pop('Avg. Avg D Kbps'), df1.pop('Avg. Avg D Kbps'))
    dfout['Latency']  = np.subtract(df2.pop('Avg Lat Ms'),df1.pop('Avg Lat Ms'))
    dfout.dropna(axis=0,inplace=True)
    dfout = dfout.merge(gdp, how='inner', on='Country')
    dataframes.append(dfout)

In [44]:
final_dataset = pd.concat(dataframes, axis=0)
final_dataset

     Mobile         Country   Upload  Download  Latency  GDP Growth
0       0.0     Afghanistan    428.0     356.0    -20.0   -1.934778
1       0.0         Albania   5327.0    7265.0     -6.0   -3.311239
2       0.0         Algeria   -133.0    1447.0    -15.0   -5.480992
3       0.0         Andorra  55214.0   57985.0      3.0  -11.956058
4       0.0          Angola    439.0    -742.0     15.0   -4.040510
..      ...             ...      ...       ...      ...         ...
146     1.0  United Kingdom  -3234.0  -27993.0     -1.0   -9.790240
147     1.0   United States  -3934.0  -16948.0      8.0   -3.486140
148     1.0         Uruguay  -2676.0  -11680.0     -4.0   -5.858721
149     1.0      Uzbekistan   3270.0   17540.0    -12.0    1.647797
150     1.0         Vanuatu  -4920.0  -12248.0     24.0   -9.235328

[1220 rows x 6 columns]

In [48]:
final_dataset.to_csv("./cleaned_dataset.csv", index=False)

In [49]:
load_test = pd.read_csv("./cleaned_dataset.csv")
load_test

      Mobile         Country   Upload  Download  Latency  GDP Growth
0        0.0     Afghanistan    428.0     356.0    -20.0   -1.934778
1        0.0         Albania   5327.0    7265.0     -6.0   -3.311239
2        0.0         Algeria   -133.0    1447.0    -15.0   -5.480992
3        0.0         Andorra  55214.0   57985.0      3.0  -11.956058
4        0.0          Angola    439.0    -742.0     15.0   -4.040510
...      ...             ...      ...       ...      ...         ...
1215     1.0  United Kingdom  -3234.0  -27993.0     -1.0   -9.790240
1216     1.0   United States  -3934.0  -16948.0      8.0   -3.486140
1217     1.0         Uruguay  -2676.0  -11680.0     -4.0   -5.858721
1218     1.0      Uzbekistan   3270.0   17540.0    -12.0    1.647797
1219     1.0         Vanuatu  -4920.0  -12248.0     24.0   -9.235328

[1220 rows x 6 columns]